site_name: {{ cookiecutter.project_name }}

markdown_extensions:
    - admonition

nav:
    - Home: index.md
    - Readme: readme2.md
    - Installation: installation.md
    - Usage: usage.md
    - Modules: modules.md
    - Contributing: CONTRIBUTING.md
{%- if cookiecutter.create_author_file == 'y' %}
    - Authors: AUTHORS.md
{%- endif %}
    - History: HISTORY.md
