name: Safety

on: [push]

jobs:
  build:

    runs-on:  ${{ matrix.platform }}
    strategy:
        max-parallel: 4
        matrix:
            # https://help.github.com/articles/virtual-environments-for-github-actions
            platform:
            - ubuntu-16.04
            - ubuntu-20.04
            - ubuntu-latest  # ubuntu-18.04
            - windows-2016
            - windows-latest  # windows-2019
            - macos-latest  # macOS-10.14
            python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v4
    - run: poetry --version
    - name: Install dependencies
      run: |
        poetry install -v
    - name: Run safety
      run: poetry run safety check
