name: Windows Tests

on: [push]

jobs:
  build:

    runs-on:  ${{ matrix.platform }}
    strategy:
        max-parallel: 4
        matrix:
            # https://help.github.com/articles/virtual-environments-for-github-actions
            platform:
            - windows-2016
            - windows-latest  # windows-2019
            python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v4
    - run: poetry --version
    - name: Install dependencies
      run: |
        poetry install -v
    - name: Check lint
      run: poetry run flake8 tests/ hooks/
    - name: Check sorting import
      run: poetry run isort --check tests/ hooks/
    - name: Check formating code
      run: poetry run black --check tests/ hooks/
    - name: Run tests
      run: poetry run pytest tests/
